on: [pull_request, push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Test
        run: ./build.cmd test
  release:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run BuildDockerImage
        run: ./build.cmd BuildDockerImage --tag czydobrze/api:latest