on: [pull_request, push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Test
        run: ./build.cmd test
  release:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ghcr.io/czydobre/czydobre.api:latest
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          addLatest: true